// Shared content for KI Learner — 10 screens
window.LESSONS = [
  {
    n: 1,
    eyebrow: 'BEGIN',
    title: 'Welcome to <em>KI Learner.</em>',
    kicker: 'Ten short lessons. About fifteen minutes.',
    body: "You won't learn to code. You'll learn what AI actually is, what it can do, and where it falls apart. Enough to be informed — not impressed.",
    motif: 'orbit',
  },
  {
    n: 2,
    eyebrow: '01 / DEFINITION',
    title: 'What is <em>AI?</em>',
    kicker: 'A system that finds patterns in data and uses them to make predictions.',
    body: "Modern AI isn't reasoning the way a person does. It is pattern-matching at scale. Show it millions of cat photos, it learns what 'cat' looks like. Show it the entire internet, it learns what words tend to follow other words.",
    pull: 'AI is statistics with a really good memory.',
    motif: 'pattern',
  },
  {
    n: 3,
    eyebrow: '02 / TRAINING',
    title: 'How AI <em>learns.</em>',
    kicker: 'Training data, then adjustment, then more training data.',
    body: "Models are trained on massive datasets — text, images, code. The model makes a guess, gets corrected, adjusts millions of internal weights, and tries again. Billions of times.",
    list: [
      'Books, websites, code repositories — all become training data',
      'The model adjusts weights to reduce error on each example',
      'After training, the weights are frozen — that\u2019s the released model',
    ],
    motif: 'grid',
  },
  {
    n: 4,
    eyebrow: '03 / MECHANICS',
    title: 'Tokens, <em>not words.</em>',
    kicker: 'Language models predict the next chunk of text — one piece at a time.',
    body: "Text is broken into tokens (roughly word fragments). The model predicts the most likely next token based on everything before it. Then the next. And the next.",
    demo: 'tokens',
    motif: 'stream',
  },
  {
    n: 5,
    eyebrow: '04 / CAPABILITIES',
    title: 'What AI <em>can do.</em>',
    kicker: 'Well: summarise, translate, draft, search, classify, generate.',
    body: "If a task involves recognising patterns in language, images, or structured data — there's likely an AI that's competent at it. Competent, not perfect.",
    grid: [
      ['Summarise', 'Long documents into short ones'],
      ['Translate', 'Across dozens of languages'],
      ['Draft', 'First versions of writing'],
      ['Classify', 'Sort emails, tag photos'],
      ['Search', 'Answer questions over your data'],
      ['Generate', 'Code, images, structured data'],
    ],
    motif: 'tiles',
  },
  {
    n: 6,
    eyebrow: '05 / LIMITS',
    title: "What AI <em>can't do.</em>",
    kicker: 'Reason like a person. Know what it doesn\u2019t know. Stay current.',
    body: "Models have no real understanding of truth, no memory between conversations by default, and a knowledge cutoff. They produce fluent answers regardless of whether they are right.",
    list: [
      'No live access to the world unless tools are added',
      'No reliable sense of its own confidence',
      'No real understanding — only learned associations',
      'No long-term memory between sessions by default',
    ],
    motif: 'void',
  },
  {
    n: 7,
    eyebrow: '06 / HALLUCINATIONS',
    title: 'Confidently <em>wrong.</em>',
    kicker: 'A hallucination is a fluent answer that happens to be made up.',
    body: "Because the model predicts what sounds right, not what is right, it will invent citations, dates, names, even entire studies. The wrongness is rarely flagged — it reads with the same calm tone as anything else.",
    pull: 'Fluency is not accuracy.',
    motif: 'mirror',
  },
  {
    n: 8,
    eyebrow: '07 / PROMPTING',
    title: 'How to <em>ask well.</em>',
    kicker: 'Context. Role. Format. Examples.',
    body: "Models do better when you tell them who they\u2019re writing for, in what role, in what format, with at least one example of what you want.",
    list: [
      'Context: who is this for, what\u2019s the goal',
      'Role: who should the model act as',
      'Format: list, table, paragraph, JSON',
      'Examples: one good answer beats five instructions',
    ],
    demo: 'prompt',
    motif: 'frame',
  },
  {
    n: 9,
    eyebrow: '08 / QUIZ',
    title: 'A quick <em>check.</em>',
    kicker: 'Five questions. No pressure. No score kept.',
    body: '',
    quiz: [
      { q: 'What does an AI model actually do?', a: ['Finds patterns and predicts', 'Looks up answers from a database', 'Reasons like a person'], correct: 0 },
      { q: 'What is a token?', a: ['A login key', 'A chunk of text the model works with', 'A prediction score'], correct: 1 },
      { q: 'What is a hallucination?', a: ['A model crashing', 'A fluent answer that is wrong', 'A type of training data'], correct: 1 },
      { q: 'After training, the model\u2019s weights are\u2026', a: ['Updated by every user', 'Frozen', 'Stored on your device'], correct: 1 },
      { q: 'The best prompts include\u2026', a: ['Politeness only', 'Context, role, format, examples', 'A single keyword'], correct: 1 },
    ],
    motif: 'dots',
  },
  {
    n: 10,
    eyebrow: 'COMPLETE',
    title: "That's the <em>foundation.</em>",
    kicker: 'You now know more than most people in the room.',
    body: "AI is a pattern engine. Powerful, useful, and fluent enough to fool you. Stay sceptical, ask for sources, and treat its confidence as decoration — not evidence.",
    cta: 'Restart course',
    motif: 'sun',
  },
];
